services:
  robetarme-ros2-humble-base:

    build:
      context: .
      dockerfile: Dockerfile

    image: registry.gitlab.com/certh-iti-robotics-lab/robetarme/robetarme/ros2-humble:base

    container_name: ros2_humble_base_container_name

    tty: true
    network_mode: "host"
    ipc: host

    #privileged: True

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
