################################################################################
# There are three places where your actions are needed in this compose file
# These are marked with the label `ACTIONS_NEEDED`.
################################################################################

services:
  ros2_humble_9f_development:
    build:
      context: .
      dockerfile: Dockerfile

    # ACTIONS_NEEDED
    # The name of the image consists of two parts.
    # The first is the prefix
    # `registry.gitlab.com/certh-iti-robotics-lab/robetarme/robetarme/ros2-humble-`.
    # The second part should be a unique byte in hexadecimal format.
    # In order to determine it visit:
    # https://www.random.org/cgi-bin/randbyte?nbytes=1&format=h
    # Then make sure no one is using the same id by checking the suffixes of
    # images of the same ROS version at:
    # https://gitlab.com/certh-iti-robotics-lab/robetarme/RoBetArme/container_registry.
    # Then modify line #2 of this file accordingly.
    image: registry.gitlab.com/certh-iti-robotics-lab/robetarme/robetarme/ros2-humble-9f:development

    # ACTIONS_NEEDED
    # The same naming convention applies to the container's name as well.
    # The first part is the prefix
    # `ros2_humble_`. Then the byte id, and at the end `_development_container`.
    container_name: ros2_humble_9f_development_container

    stdin_open: true
    tty: true
    network_mode: "host"
    ipc: host

    #privileged: True

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all

    volumes:

      # ACTIONS_NEEDED
      # You may communicate between the container and the host via
      # a shared directory. The name of the directory on the host should be the
      # same as the suffix of the image, prefixed with the word `shared`,
      # e.g. [shared]-[ros2-humble-9f]
      # On the container's side this directory sits at
      # `/home/robetarme_user/shared/`.
      # You should name the former but not the latter.
      # [shared]-[ros2-humble-9f] should already exist before running
      # `docker compose build` on the host.
      # You may place the shared directory wherever you like on your host,
      # but if you do so you need to modify the left-hand side of the below mapping.
      - ./shared-ros2-humble-9f:/home/robetarme_user/shared:rw

      # Mount the source code of all packages in a bind mount.
      # This means that
      # - source code modifications in runtime (in the container) persist on the
      #   host's side: you don't have to port them to the host and then build
      #   the image from scratch
      # - the image already has the source code: you don't need to
      #   `colcon build` upon entry to the container
      # - build/, install/, and log/ do not overlap between host and container
      - ./ros2_ws/src:/home/robetarme_user/ros2_ws/src:rw

      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    #user: ${USERNAME:-robetarme_user}
